version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: pg_vpn_bot
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=250MB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes:/var/lib/postgresql/data
    networks:
      - vpn_bot
    # ports:
    #   - "4356:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.ru
      PGADMIN_DEFAULT_PASSWORD: "${PG_PASS}"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - vpn_bot
    logging:
      driver: none
  vpn_bot:
    container_name: "vpn_bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - vpn_bot
    depends_on:
      - postgres
    ports:
      - 3030:3030
      - 6060:6060
  web_server:
    container_name: "web_server"
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile.server
    working_dir: "/usr/src/server"
    # volumes:
    #   - ./server:/usr/src/server
    command: python3 -m server
    restart: always
    env_file:
      - ".env"
    networks:
      - vpn_bot
    depends_on:
      - postgres
    ports:
      - 6000:6000
  cron-container:
    build:
      context: .
      dockerfile: Dockerfile.cron
    working_dir: "/usr/src/cron"
    volumes:
      - ./cron/crontabs:/var/spool/cron/crontabs
      - ./cron/bash:/usr/src/cron
    command: crond -l 2 -f
    networks:
      - vpn_bot
    depends_on:
      - web_server
      - postgres

networks:
  vpn_bot:
    driver: bridge
